### ISSUE TITLE
[0.9] fail to install on netbeans7.0beta

### ISSUE THREAD

**Issue by zhangpy** [dstepanov/coffeescript-netbeans#1]
## only beta has ruby support, I have to stay on this version. Could you help to make it work on that? thanks.

error
Some plugins require plugin Swing Layout Extensions integration to be installed.
The plugin Swing Layout Extensions integration is requested in version >= 1.16.1 but only 1.15 was found.  The following plugin is affected:       CoffeeScript Netbeans 
Some plugins require plugin Rhino IDE JavaScript Handler to be installed.
The plugin Rhino IDE JavaScript Handler is requested in version >= 1.112.1 but only 1.111 was found.  The following plugin is affected:       CoffeeScript Netbeans 
Some plugins require plugin Progress API to be installed.
The plugin Progress API is requested in version >= 1.23.1 but only 1.22 was found.  The following plugin is affected:       CoffeeScript Netbeans 
Some plugins require plugin Common Scripting Language API (new) to be installed.
The plugin Common Scripting Language API (new) is requested in version >= 2.14.1.2.1.1.6 but only 2.10.0.2.1.1.5 was found.  The following plugin is affected:       CoffeeScript Netbeans 
Some plugins require plugin MIME Lookup API to be installed.
The plugin MIME Lookup API is requested in version >= 1.21.1 but only 1.20 was found.  The following plugin is affected:       CoffeeScript Netbeans 
Some plugins require plugin Editor Settings to be installed.
The plugin Editor Settings is requested in version >= 1.35.1 but only 1.34 was found.  The following plugin is affected:       CoffeeScript Netbeans 
Some plugins require plugin HTML Lexer to be installed.
The plugin HTML Lexer is requested in version >= 1.12.1 but only 1.11 was found.  The following plugin is affected:       CoffeeScript Netbeans 
Some plugins require plugin Lexer to be installed.
The plugin Lexer is requested in version >= 1.38.1.1 but only 1.37.0.1 was found.  The following plugin is affected:       CoffeeScript Netbeans 
Some plugins require plugin Options Dialog and SPI to be installed.
The plugin Options Dialog and SPI is requested in version >= 1.21.1 but only 1.20 was found.  The following plugin is affected:       CoffeeScript Netbeans 
Some plugins require plugin Parsing API to be installed.
The plugin Parsing API is requested in version >= 1.39.1.6 but only 1.36.0.5 was found.  The following plugin is affected:       CoffeeScript Netbeans 
Some plugins require plugin Editor Hints to be installed.
The plugin Editor Hints is requested in version >= 1.17.1.7.8 but only 1.16.0.7.4 was found.  The following plugin is affected:       CoffeeScript Netbeans 
Some plugins require plugin UI Utilities API to be installed.
The plugin UI Utilities API is requested in version >= 7.30.1 but only 7.29 was found.  The following plugin is affected:       CoffeeScript Netbeans 
Some plugins require plugin Execution API to be installed.
The plugin Execution API is requested in version >= 1.21.1 but only 1.20 was found.  The following plugin is affected:       CoffeeScript Netbeans 
Some plugins require plugin File System API to be installed.
The plugin File System API is requested in version >= 7.46.1 but only 7.42 was found.  The following plugin is affected:       CoffeeScript Netbeans 
Some plugins require plugin I/O APIs to be installed.
The plugin I/O APIs is requested in version >= 1.26.1 but only 1.25 was found.  The following plugin is affected:       CoffeeScript Netbeans 
Some plugins require plugin Datasystems API to be installed.
The plugin Datasystems API is requested in version >= 7.20.1 but only 7.19 was found.  The following plugin is affected:       CoffeeScript Netbeans 
Some plugins require plugin Nodes API to be installed.
The plugin Nodes API is requested in version >= 7.20.1 but only 7.18 was found.  The following plugin is affected:       CoffeeScript Netbeans 
Some plugins require plugin Text API to be installed.
The plugin Text API is requested in version >= 6.36.1 but only 6.33 was found.  The following plugin is affected:       CoffeeScript Netbeans 
Some plugins require plugin Utilities API to be installed.
The plugin Utilities API is requested in version >= 8.14.1 but only 8.9 was found.  The following plugin is affected:       CoffeeScript Netbeans 
Some plugins require plugin Lookup API to be installed.
The plugin Lookup API is requested in version >= 8.6.1 but only 8.5 was found.  The following plugin is affected:       CoffeeScript Netbeans 
Some plugins require plugin Window System API to be installed.
The plugin Window System API is requested in version >= 6.39.1 but only 6.35 was found.  The following plugin is affected:       CoffeeScript Netbeans  Some plugins not installed to avoid potential installation problems.

**Comment by dstepanov** [comment]
NB 7.0 already has ruby support, download it from Tools -> Plugins

**Comment by zhangpy** [comment]
Oh, thanks.
