### ISSUE TITLE
File Locking

### ISSUE THREAD

**Issue by JeffOnWire** [dstepanov/coffeescript-netbeans#19]
Hope this is an appropriate post for this site. I posted over at the netbeans site but they suggested I contact the plugin author.

Having a problem on two different Win 7 64 bit computers. Just recently (in the last two weeks) downloaded Netbeans and the coffeescript plugin to both computers. both computers are recent builds (past 2 months) and neither had the JDK or Netbeans loaded before. I'm only using Netbeans with the coffeescript plugin right now (not using Netbeans for any other purpose so not sure if the file locking problem occurs in other contexts).

Problem is that I create a new coffeescript file and compile it. This creates a new javascript file. Subsequent attempts to re-compile the file frequently fail with this message:

org.openide.filesystems.FileAlreadyLockedException: C:\Users\myusername\Documents\NetBeansProjects\HQ 1072 Reservation Calendar\src\end-test.js
        at org.netbeans.modules.masterfs.filebasedfs.fileobjects.LockForFile.registerLock(LockForFile.java:114)
        at org.netbeans.modules.masterfs.filebasedfs.fileobjects.LockForFile.tryLock(LockForFile.java:103)
        at org.netbeans.modules.masterfs.filebasedfs.fileobjects.FileObj.lock(FileObj.java:353)
        at org.openide.filesystems.FileObject.delete(FileObject.java:363)
        at coffeescript.nb.CoffeeScriptAction$CompilerTask.compile(CoffeeScriptAction.java:245)
        at coffeescript.nb.CoffeeScriptAction$ConsoleOutputCompileTask.run(CoffeeScriptAction.java:194)
        at org.netbeans.core.execution.RunClassThread.run(RunClassThread.java:153)

Attempts to open the file or view file properties fail. After variable time delay the file eventually unlocks, or closing and reopening Netbeans unlocks the file.

Netbeans Information
Product Version: NetBeans IDE 7.1.1 (Build 201203012225)
Java: 1.7.0_03; Java HotSpot(TM) 64-Bit Server VM 22.1-b02
System: Windows 7 version 6.1 running on amd64; Cp1252; en_US (nb)
User directory: C:\Users\oigsdgbrewej.netbeans\7.1.1
Cache directory: C:\Users\oigsdgbrewej.netbeans\7.1.1\var\cache

As I said before it's happening on two different machines:

Windows 7 Enterprise Service Pack 1
Processor: Intel(R) Xeon(TM) CPU X5570 @ 2.93GHz 2.93GHz (2 processors)
Installed memory (RAM): 6.00 GB
System type: 64-bit Operating System

Windows 7 Enterprise Service Pack 1
Processor: Intel(R) Core(TM) i7-2720QM CPU @ 2.20GHz 2.20GHz
Installed memory (RAM): 8.00 GB
System type: 64-bit Operating System

**Comment by dstepanov** [comment]
I will try to fix it

**Comment by dstepanov** [comment]
Should be fixed in next release

**Comment by JeffOnWire** [comment]
Just wanted to say THANK YOU! I was working away a few days ago when suddenly a little popup window told me that an update was ready for Netbeans. I updated, restarted, and have coding away happily ever since. Not a single file lock. Everything is working great. Thank you very much for fixing this.
