### ISSUE TITLE
Coffee script Project Support

### ISSUE THREAD

**Issue by swistak** [dstepanov/coffeescript-netbeans#2]
Hey.
It would be awesome to have support for coffee script projects.

**Comment by dstepanov** [comment]
I'm planning project support probably without building support I'm not sure right now what would be the best solution to implement it

**Comment by swistak** [comment]
I think best solution would be to utilize already existing generators (like one from express framework or zappa) to provide people with ready to use examples. Besides that I think it could be as simple as possible. I currently use c++ project for my coffeescripts (since it's pure cs proejct based on node.js)

**Comment by dstepanov** [comment]
I will create basic cs project with configurable command line params for run/test etc

**Comment by dstepanov** [comment]
There is a support now for projects with Cakefile

**Comment by swistak** [comment]
Great! Thanks a lot :)
