### ISSUE TITLE
Ability to create project with existing sources

### ISSUE THREAD

**Issue by danhstevens** [dstepanov/coffeescript-netbeans#22]
There doesn't seem to be a way to create a CoffeeScript project that already has existing source. This is challenging when using Git repos, etc. Could you add the capability to create a NetBeans CoffeeScript project using existing sources?

Thanks,
Dan

**Comment by dstepanov** [comment]
It should recognize a CoffeeScript project when you have a Cakefile in a folder, just create an empty one.

**Comment by danhstevens** [comment]
Indeed it does. Thanks!
