### ISSUE TITLE
Can't insert single quote

### ISSUE THREAD

**Issue by lboynton** [dstepanov/coffeescript-netbeans#25]
There are some instances where I can't insert a single quote in a .coffee file. When pressing the key, it seems that it might be inserted but deleted straight away.

Closing the file in the editor and opening it again fixes the issue for a little while.

I've noticed the problem in NB 7.2 and 7.3 and version 1.2 of the plugin.

**Comment by antev** [comment]
+1. It's seems to be caused by some symbols. e.g. can't type `a = ''`
`
a = 
b = '²'
`

**Comment by dstepanov** [comment]
Can you reproduce it every time?

Did it work before version 1.2?

**Comment by antev** [comment]
I can reproduce it every time with "²" symbol. I use NB 7.3 and plugin 1.2. I didn't use other versions.

**Comment by dstepanov** [comment]
Please post steps how to reproduce it and your environment. Also try it in the javascript editor.

I don't know what could cause it, it could be a netbeans bug.

**Comment by antev** [comment]
Steps:
1. Create new empty coffee file 
2. Copy next strings to it:
`a = ''`
`b =`
`c = '²'`
`d = ''`
3. You won't be able to add or remove the `'` symbol before the `²` symbol (in lines 1, 2, 3) but you it will works fine after the `²` symbol (in lines 3 and 4).

Environment - NB 7.3, plugin 1.2, ubuntu 11.10.

It works fine with js files, also it works with coffee files when the plugin is disabled.

**Comment by celwell** [comment]
I also experience this issue at seemingly random times. I have a Cakefile open right now in Netbeans 7.3 and using version 1.3 of the CoffeeScript Netbeans plugin. I can't delete any single-quote in the file. By 'delete' i mean using backspace or the delete button. I'm on Windows 7.

**Comment by dstepanov** [comment]
Please open log 'Menu -> View -> IDE log' at checkout if there is an exception while you are trying to delete a character.

**Comment by celwell** [comment]
Nope, nothing is logged in the IDE log.
