### ISSUE TITLE
How can I modify the format of the generated Javascript, I need to have 4spaces for tabs

### ISSUE THREAD

**Issue by nelsonomuto** [dstepanov/coffeescript-netbeans#26]

**Comment by dstepanov** [comment]
I'm using coffeescript compiler to produce js and it doesn't have an option to have spaces instead of tabs.

**Comment by nelsonomuto** [comment]
I believe the coffeescript compiler can generate better formatted javascript than what the plugin is currently churning out. I'll take a jab at this and make a pull request.
