### ISSUE TITLE
Compile on *nix system - Login shell

### ISSUE THREAD

**Issue by atmattpatt** [dstepanov/coffeescript-netbeans#27]
Is there a reason that CoffeeScriptNodeJSCompiler.createValidateProcessBuilderNix() and CoffeeScriptNodeJSCompiler.createCompileProcessBuilderNix() uses Bash as a login shell?

Running as a login shell with source the current user's .bashrc or .bash_profile files, which may cause side effects.  Those side effects are then included in the output JavaScript file.

For example, if my .bash_profile contains the following:

```
echo -n "Load average: " && cat /proc/loadavg
```

When I go to compile a .coffee file through NetBeans, the resulting JavaScript file uses something like:

```
Load average: 0.00 0.01 0.05 1/84 16976
// Generated by CoffeeScript 1.6.1
(function() {
    var _this = this;
    // ...
```

Which of course is not valid JS.

I've been trying to think of a reason for using a login shell but I've come up empty.  Can the `-l` be removed?

**Comment by dstepanov** [comment]
Honestly I'm not a bash/shell expert, I will try to remove it.
