### ISSUE TITLE
Can't install in NetBeans 6.9.1

### ISSUE THREAD

**Issue by msolovyov** [dstepanov/coffeescript-netbeans#3]
Tried to install it on nb 6.9.1 but received the following requirement errors: https://gist.github.com/1013770

I'm using nb 6.9.1 still until the ruby support is back in 7.0.

Is there a possibility of having this coffeescript plugin working in 6.9.1?

**Comment by dstepanov** [comment]
NB 7.0 already has the ruby support, download it from Tools -> Plugins

**Comment by piousbox** [comment]
Netbeans sites say, ruby support has been discontinued. I downgraded to 6.9.1 for ruby support.
