### ISSUE TITLE
Indentation features

### ISSUE THREAD

**Issue by danes** [dstepanov/coffeescript-netbeans#4]
Hi,

is there any plan on improving editor indentation?

The biggest pain point right now is having to manually indent every new line as it starts at 0. Using tab to indent also doesn't recognize the correct indentation level like in other Netbeans file editors.

A really simple solution to start would be to just maintain the indentation level of the previous line.

To make it full-featured, you could also consider the following:
- smart indentation that auto-indents based on syntax (detects start / end of code blocks etc.)
- tab options (no. of tabs / use spaces or tabs etc.)
- using tab, shift-tab to indent
- auto-format code

**Comment by dstepanov** [comment]
Yeah, new line indentation at 0 is very annoying, I will try to implement that simple solution. Full indention/formatting requires implementing AST which is now an easy task. I has an idea that it would help to improve current lexer to be fully identical to the CS lexer and then use grammar.coffee's rules to generate AST parser/tree walker.

"- tab options (no. of tabs / use spaces or tabs etc.)
- using tab, shift-tab to indent"

Global tab formatting options and tab/s-tab to indent works for me in the latest version.

**Comment by dstepanov** [comment]
Resolved in 0.9.1
