### ISSUE TITLE
Code Folding

### ISSUE THREAD

**Issue by nickyhajal** [dstepanov/coffeescript-netbeans#6]
Thanks for this great extension!

Would it be possible to include code-folding in a later release?

**Comment by dstepanov** [comment]
Probably, I have never used a code-folding before :) anyway I don't think it would be complicated to implement.

**Comment by nickyhajal** [comment]
Hi there :)

Just thought I'd pop back in to see what it might take to move this forward. 

What I'm realizing is that basically, all it would need is to add a fold at each indent level.

Here's a screenshot of what I'm hoping to bring from JavaScript to Coffee, just for completeness: http://dl.dropbox.com/u/1916622/screenshots/netbeans-folding.png

I've never workend on a netbeans plugin before but if you could give me even the briefest point in the right direction, I may be able to start figuring it out from there. 

Thanks for your awesome work on this plugin!

-Nicky

**Comment by dstepanov** [comment]
I have commited example how to implement it, all you need is CoffeeScriptStructureScanner and method folds. Implementation folds by default region with offset 50-200.

There is no abstract syntax tree so you need to read tokens to figure out what text regions could be folded.

**Comment by dstepanov** [comment]
Replaced example with comments folding, you probably want to fold methods, functions etc. the way to do it is to have lexer recognize indention just like cs's lexer does it.

**Comment by dstepanov** [comment]
I have spent some time to implement it :), now it should fold by indent/outdent. If you want to check it out try to build the plugin from sources.

**Comment by nickyhajal** [comment]
Hey, thanks so much, sounds great! I'm probably just being stupid (don't know much about building an nbm) but when I try to build the source I get: 

/Users/nicky/Downloads/dstepanov-coffeescript-netbeans-250d473/nbproject/build-impl.xml:37: Path to 'platform' cluster missing in ${cluster.path} property or using corrupt Netbeans Platform (missing harness).

Any idea how to get it past that?

Thanks!

**Comment by dstepanov** [comment]
Try to close and open project. If this will not help I will upload new version.

**Comment by nickyhajal** [comment]
Hm - now I get:  

You must define 'nbplatform.${nbplatform.active}.harness.dir'

Seems like that must be a problem with my setup - it does have a NB Platform and a Java Platform set in the project properties. 

Sorry for the hassle :)

**Comment by dstepanov** [comment]
I have uploaded new version.

**Comment by nickyhajal** [comment]
This is perfect, thank you so much!
